[build]
  base = ""
  publish = "."
  command = ""
  ignore = "git diff --quiet HEAD^ HEAD backend/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Ignorer backend folder
[[headers]]
  for = "/backend/*"
  [headers.values]
    X-Robots-Tag = "noindex"
